name: pamasuka
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.3
  image_picker: ^1.0.7
  http: ^0.13.6
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/Samalonian_app.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/Samalonian_app.png"
